### ISSUE TITLE
Issue with jax.config in energy.py on Google Colab

### ISSUE THREAD

**Issue by TakumiOtagaki** [rkruegs123/jax-rnafold#4]
Hello,

I tried running jax-rnafold on Google Colab, but it seems there have been some updates related to jax.config, which caused an error in energy.py.

At line 7 in src/energy.py:
```py
# from jax.config import config
from jax import config
```

After modifying the import statement like this, the issue was resolved.

Could you let me know the version of JAX used during development? There might be other potential errors lurking, so I’d appreciate any additional guidance.

Thank you!

**Comment by rkruegs123** [comment]
Hi Takumi,

I updated the repo to reflect these changes in newer versions of JAX. Unfortunately I upgraded my environment since I created the repo, but I think I was using ~ 0.4.15. Let me know if you continue to have issues and we can work them out together.

FWIW, this "config" thing is the largest breaking change i've noticed with the newer versions, and it's a pretty quick fix ;)

Everything should work now :)

-Ryan
